### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by tburleyinfo** [bendichter/tenseflow#7]
Not an issue, but this tool does work with python3. You have to reinstall openssl and use the command 
LDFLAGS=-L/usr/local/opt/openssl/lib pip3 install mysqlclient for the my sql dependency. 

You also have to comment the `raise StopIteration` line in the init file in pattern library. You'll see this error when you run your initial tenseflow tests.

**Comment by Joonsun-Hwang** [comment]
> Not an issue, but this tool does work with python3. You have to reinstall openssl and use the command
> LDFLAGS=-L/usr/local/opt/openssl/lib pip3 install mysqlclient for the my sql dependency.
> 
> You also have to comment the `raise StopIteration` line in the init file in pattern library. You'll see this error when you run your initial tenseflow tests.

Thanks to your point, I was able to solve the StopIteration error. Thank you.

**Comment by bendichter** [comment]
Thanks @tburleyinfo and @Joonsun-Hwang! Through you comments I realized how to get it working in python 3! It now works without any alterations in python 3.6.

I made this as a little fun project while in grad school. I think it's cool that people are using it. Did you find it useful for your purposes?
